package Connection;

public enum MessageType {
    REQUEST_NAME_USER,
    TEXT_MESSAGE,
    NAME_ACCEPTED,
    USER_NAME,
    NAME_USED,
    NEW_USER_ADDED,
    DISCONNECT_USER,
    REMOVED_USER,
    MESSAGE_FROM_SERVER,
    CONFIRM_DISCONNECT
}